/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dortIslem;

import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class ServerUI extends javax.swing.JFrame {

    TCP_Server server;
    TCP_Client client;

    /**
     * Creates new form ServerUI
     */
    public ServerUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        easy_button = new javax.swing.JRadioButton();
        medium_button = new javax.swing.JRadioButton();
        hard_button = new javax.swing.JRadioButton();
        start_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("->ROOMS");

        buttonGroup1.add(easy_button);
        easy_button.setText("Easy");
        easy_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easy_buttonActionPerformed(evt);
            }
        });

        buttonGroup1.add(medium_button);
        medium_button.setText("Medium");
        medium_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medium_buttonActionPerformed(evt);
            }
        });

        buttonGroup1.add(hard_button);
        hard_button.setText("Hard");
        hard_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hard_buttonActionPerformed(evt);
            }
        });

        start_button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        start_button.setText("→");
        start_button.setEnabled(false);
        start_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(medium_button)
                    .addComponent(easy_button)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hard_button)
                        .addGap(108, 108, 108)
                        .addComponent(start_button, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(easy_button)
                .addGap(18, 18, 18)
                .addComponent(medium_button)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(hard_button)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(start_button, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private int selection;
    private void hard_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hard_buttonActionPerformed
        // TODO add your handling code here:
        start_button.setEnabled(true);
        selection = 3;
        TCP_Server.setInfo(selection);
    }//GEN-LAST:event_hard_buttonActionPerformed

    private void start_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start_buttonActionPerformed
        // TODO add your handling code here:        
        if (easy_button.isSelected() || medium_button.isSelected() || hard_button.isSelected()) {
            try {
                int port = 44444;
                server = new TCP_Server();
                server.start(port);
                this.hide();
                new ClientUI().setVisible(true);
            } catch (IOException ex) {
                System.out.println("Error - jButtonStartActionPerformed : " + ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select room");
        }
    }//GEN-LAST:event_start_buttonActionPerformed

    private void easy_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easy_buttonActionPerformed
        // TODO add your handling code here:
        start_button.setEnabled(true);
        selection = 1;
        TCP_Server.setInfo(selection);
    }//GEN-LAST:event_easy_buttonActionPerformed

    private void medium_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medium_buttonActionPerformed
        // TODO add your handling code here:
        start_button.setEnabled(true);
        selection = 2;
        TCP_Server.setInfo(selection);
    }//GEN-LAST:event_medium_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton easy_button;
    private javax.swing.JRadioButton hard_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton medium_button;
    private javax.swing.JButton start_button;
    // End of variables declaration//GEN-END:variables
}
